config/routes.rb
Traffic::Application.routes.draw do

  devise_for :users

  root :to => "static_pages#home"

  #
  # Resources
  #

  resources :locations, only: [:index, :create, :destroy]

  resources :users, only: [:show, :new, :create]

  authenticated :user do
    root :to => "static_pages#home"
  end

  #
  # Custom routes
  #

  # User routes
  [:locations].each do |action|
    match "/user/:id/#{action}" => "users##{action}", as: "user_#{action}"
  end

  # Static page routes
  [:locations, :home].each do |action|
    match "#{action}" => "static_pages##{action}", as: "#{action}", via: "get"
  end

  # Location routes
  [:all].each do |action|
    match "/locations/#{action}" => "locations##{action}"
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :locations, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :js, :html

  #
  # CRUD
  #

  def index
    @locations = current_user.locations.all
  end

  def create
    lat = params["lat"]
    lng = params["lng"]

    @location = Location.new(lat: lat, lng: lng, user_id: current_user.id)
    if @location.save
      render status: 200
    else
      render status: 500
    end

  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    render status: 200
  end

  #
  # Custom actions
  #

  def all
    @locations = Location.all
    render "shared/show_locations"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @users = User.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:locations, :show]

  respond_to :js, :html

  #
  # CRUD
  #

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to location_path
    else
      render 'new'
    end
  end

  def show
  end

  #
  # Custom
  #

  def locations
    user_id = params[:id]
    @user = User.find(user_id)
    @locations = @user.locations.all
    render "shared/show_locations"
  end

  private

  # TODO
  #
  # def params[:user]
  #   params.require(:user).permit(:email, :password, :password_confirmation)
  # end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
  	<p>Oneline Traffic Data © <%= Time.now.year %> All Rights Reserved</p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Online Traffic Data", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Blog",    '#' %></li>
          <li><a href="https://twitter.com/SimplyTraffic">Twitter</a></li>
          <% if user_signed_in? %>
            <li>
            <%= link_to('Locations', locations_path, :method => :get) %>
            </li>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>
            </li>
          <% end %>
          <li><%= link_to "Request More Info", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Traffic</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= GMAP_API %>&sensor=false">
    </script>

    <%= yield :head %>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= render 'layouts/footer' %>

  </body>

</html>

app/views/locations/destroy.js.erb
var
  location_id = "<%= @location.id %>",
  $item = $("p[data-id='"+location_id+"']");

$item.fadeOut()

app/views/locations/index.html.erb
<h2>My <%= pluralize(@locations.size, "location") %></h2>

<h3>My user id: <%= current_user.id %></h3>

<% @locations.each_with_index do |location, index| %>

  <p data-id="<%= location.id %>">
    Location <%= index+1 %>: Lat: <%= location.lat %>, Long: <%= location.lng %>, user: <%= location.user_id %><br />
    <%= link_to "Delete",
      location_path(location.id),
      :confirm => "Are you sure?",
      :method => :delete,
      :remote => true %>
  </p>

<% end %>

app/views/shared/show_locations.js.erb
// Log how many locations came back from database call
var
  location_count = "<%= @locations.size %>",
  locations_placed = 0;
console.log(location_count+" locations returned from databse");

<% @locations.each do |location| %>

  var marker_image;
  var metaData = "<%= location.to_json %>";

  // http://mabp.kiev.ua/2010/01/12/google-map-markers/
  <% if location.user_id == current_user.id %>
    marker_image = "http://labs.google.com/ridefinder/images/mm_20_green.png";
  <% else %>
    marker_image = "http://labs.google.com/ridefinder/images/mm_20_red.png";
  <% end %>

  var
    lat = "<%= location.lat %>",
    lng = "<%= location.lng %>",
    googleLatLng = new google.maps.LatLng(lat, lng);

  // Only place marker if it exists within the area of the current map view
  if( map.getBounds().contains( googleLatLng ) ) {
     placeMarker({
      location: googleLatLng,
      draggable: false,
      icon: marker_image,
      metaData: metaData
    });

    locations_placed++;

  } else {
    console.log("marker not placed. out of map view area.");
  }

<% end %>

console.log("placed "+locations_placed+" markers");

app/views/static_pages/home.html.erb
<script type="text/javascript">

  // Enable the visual refresh
  google.maps.visualRefresh = true;

  // Initialize google map
  google.maps.event.addDomListener(window, 'load', initHomePageMap);

</script>

<div id="map-canvas" style="height:500px;"></div>

<p><%= link_to "Clear map", "javascript:void(0)", :class => "clear-map" %></p>

<p><span class="markers-count">0</span> markers loaded</p>

<p>
  Show locations for user:
</p>

<ul>
  <li>
    <%= link_to "All users",
      locations_all_path,
      :class => "user-show-locations",
      :remote => true %>
  </li>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.email} (id: #{user.id})",
      user_locations_path(user.id),
      :class => "user-show-locations",
      :remote => true %>
    </li>
  <% end %>
</ul>

<ul class="locations">
  <!--new markers will be shown here-->
</ul>

app/views/static_pages/locations.html.erb
<h1>Locations</h1>

<% if user_signed_in? %>
	
<% else %>
    <h1>You have to be signed in to see this</h1>
<% end %>

app/views/users/locations.js.erb
<% @locations.each do |location| %>

  var marker_image;
  var metaData = "<%= location.to_json %>";

  <% if location.user_id == current_user.id %>
    marker_image = "http://maps.google.com/intl/en_us/mapfiles/ms/micons/green-dot.png";
  <% else %>
    marker_image = "http://maps.google.com/intl/en_us/mapfiles/ms/micons/red-dot.png";
  <% end %>

  var
    lat = "<%= location.lat %>",
    lng = "<%= location.lng %>",
    googleLatLng = new google.maps.LatLng(lat, lng);

  placeMarker({
    location: googleLatLng,
    draggable: false,
    icon: marker_image,
    metaData: metaData
  });

<% end %>

app/views/users/new.html.erb
<h1>Register now!</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>